const NEVER = "never",
ALWAYS = "always",
ALWAYS_MULTILINE = "always-multiline",
MULTILINE = "multiline",
CONSISTENT = "consistent",
CONSECUTIVE = "consecutive",
AS_NEEDED = "as-needed",
EXPLICIT = "explicit",
ALLOW = "allow",
STRICT = "strict",
ANY = "any",
ALL = "all",
STAR = "*",
FIRST = "first",
LAST = "last",
BEFORE = "before",
AFTER = "after",
ABOVE = "above",
BELOW = "below",
BESIDE = "beside",
INSIDE = "inside",
OUTSIDE = "outside",
SINGLE = "single",
DOUBLE = "double",
MULTI = "multi",
BOTH = "both";

export {
  NEVER,
  ALWAYS,
  ALWAYS_MULTILINE,
  MULTILINE,
  CONSISTENT,
  CONSECUTIVE,
  AS_NEEDED,
  EXPLICIT,
  ALLOW,
  STRICT,
  ANY,
  ALL,
  STAR,
  FIRST,
  LAST,
  BEFORE,
  AFTER,
  ABOVE,
  BELOW,
  BESIDE,
  INSIDE,
  OUTSIDE,
  SINGLE,
  DOUBLE,
  MULTI,
  BOTH,
};
